### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by wael-mos** [Node-NTRIP/rtcm#2]
The decode-encode.js file is using TextDecoder and TextEncoder without import and may provoc crash on few devices.
To fix it i simply add the import `TextDecoder = require("util").TextDecoder;`

SO: Ubuntu 20.04.2 LTS
Node version: v10.19.0
Npm: 6.14.4

**Comment by kaido42** [comment]
using newer node helps also.

**Comment by nebkat** [comment]
70b70c7682385c99fe8653db0a7b498ad9792568
