### ISSUE TITLE
targetStart out of range in Buffer.copy() line 70 in stream.ts  

### ISSUE THREAD

**Issue by romaintribout** [Node-NTRIP/rtcm#3]
var this.index can be negative (line 110 - with "this.index -= potential")

when this.index is negative, line 70 crash.
chunk.copy(this.buffer, this.index, chunkOffset, chunkOffset + copyBytes);

with this test after line 110, I have no crash:
if (this.index < 0) {
      this.index = 0
}

**Comment by nebkat** [comment]
0941d62e32ec6607171f026ef67fc176fadd5f26
